#!/usr/bin/env bash
# a script that setup ubuntu machine and install nginx

sudo apt-get -y update;
sudo apt-get -y install nginx;
sudo ufw allow 'Nginx HTTP';
echo "Hello World!" > /var/www/html/index.nginx-debian.html;
sudo service nginx start;
