#!/usr/bin/env bash
# a Bash script that displays numbers from 1 to 20 and do some tricks in between
i=1
while [ $i -lt 21 ]
do
	echo "$i"
	case $i in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
		*)
	esac
	i=$(( i+1 ))
done
